apiVersion: v1
kind: Namespace
metadata:
  name: kl-quorum
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: boot-node-key
  namespace: kl-quorum
data:
  nodekey: "a8a535aeca0652612445543e79b6975c7470edbe8fc4ec9921dc6eeccdc7200d"

---
apiVersion: v1
kind: Service
metadata:
  name: boot-node-service
  namespace: kl-quorum
spec:
  selector:
    app: boot-node
  ports:
  - port: 3031
    targetPort: 3031

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: kl-quorum
spec:
  selector:
    matchLabels:
      app: boot-node
  template:
    metadata:
      labels:
        app: boot-node
    spec:
      containers:
      - name: bootnode
        image: jpmorganchase/quorum
        imagePullPolicy: Never
        command: ["bootnode"] 
        args: ["-nodekey", "/qdata/nodekey"] 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3031
        volumeMounts:
        - mountPath: /qdata/nodekey
          subPath: nodekey
          name: qdata-0
      volumes:
      - name: qdata-0
        configMap: 
          name: boot-node-key
