apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
spec:
  capacity:
    storage: 5Gi  # Replace with the desired storage size
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/samip/kl/quorum-tools/examples/qdata_1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Replace with the desired storage size, should match the PV size
  selector:
    matchLabels:
      pv-name: my-local-pv