kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /Users/samip/Documents/kl/quorum-tools/examples/qdata_1/
    containerPath: /qdata1
    propagation: HostToContainer
  - hostPath: /Users/samip/Documents/kl/quorum-tools/examples/qdata_2/
    containerPath: /qdata2
    propagation: HostToContainer
  - hostPath: /Users/samip/Documents/kl/quorum-tools/examples/qdata_3/
    containerPath: /qdata3
    propagation: HostToContainer
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"